FROM nvidia/cuda:12.6.0-runtime-ubuntu20.04
WORKDIR /app
RUN apt-get update && apt-get install -y python3-pip python3-dev
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY server.py .
CMD ["python3", "server.py"]