FROM nvidia/cuda:12.4.1-runtime-ubuntu20.04
WORKDIR /app
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y python3.9 python3.9-dev python3-pip
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3.9", "client.py"]